In [ ]:
from __future__ import print_function
from google.colab import files 

import io
import pandas as pd


  
#Code to upload the dataset from your computer as a dataframe
df=pd.read_csv("/content/final_df.csv")

In [ ]:
#Code to take first 10,000 instances of the dataset.
df = df.iloc[:10000, :]
df.shape

(10000, 4)

In [ ]:
df.head()

,Unnamed: 0,product,desc,product_id
0,0,Strap top,solid jersey basic basics everyday womens shou...,1
1,1,Strap top (1),stripe jersey basic basics everyday womens sho...,2
2,2,OP T-shirt (Idro),solid clean lingerie womens lingerie visible m...,3
3,3,20 den 1p Stockings,solid tights basic tigh socks nightwear womens...,4
4,4,Shape Up 30 den 1p Tights,solid tights basic tigh socks nightwear womens...,5

In [ ]:
import nltk
nltk.download('punkt')
from nltk import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
#Tokenization of data
df['desc'] = df.apply(lambda row: nltk.word_tokenize(row['desc']), axis=1)

In [ ]:
#Lemmatization
import nltk
nltk.download('omw-1.4')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

def lemmatizer(text):
  lemm = [wordnet_lemmatizer.lemmatize(word) for word in text]
  lemm = ' '.join(lemm)
  return lemm
  
df['desc']=df['desc'].apply(lambda x:lemmatizer(x))

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df.head(10)

,Unnamed: 0,product,desc,product_id
0,0,Strap top,solid jersey basic basic everyday woman should...,1
1,1,Strap top (1),stripe jersey basic basic everyday woman shoul...,2
2,2,OP T-shirt (Idro),solid clean lingerie woman lingerie visible mi...,3
3,3,20 den 1p Stockings,solid tights basic tigh sock nightwear woman w...,4
4,4,Shape Up 30 den 1p Tights,solid tights basic tigh sock nightwear woman a...,5
5,5,Support 40 den 1p Tights,solid tights basic tigh sock nightwear woman e...,6
6,6,200 den 1p Tights,solid tights basic tigh sock nightwear woman m...,7
7,7,SWEATSHIRT OC,pattern basic baby complement essential baby p...,8
8,8,Alice BANDEAU 2-p,stripesolid casual lingerie woman lingerie top...,9
9,9,Frugan longsleeve,solid jersey basic basic everyday woman neckli...,10

In [ ]:
df.to_csv('preprocessed_data.csv')